Repository CAUCSE/CAUSW_frontend, pull requests merged in 2024-03, with the labels that each got.

#85 [FIX] 대댓글 수정, 삭제 기능 개선 + 동아리 캐러셀 반응형 추가
  src/components/Atoms/Button.tsx
  src/pages/auth/signIn/SignInPage.tsx
  src/pages/board/postDetail/components/ReplyComment/ReplyCommentContainer.tsx
  src/pages/circle/home/CircleHomePage.tsx
  src/pages/circle/home/components/WebSlider/CircleWebSlideCard.tsx
  src/pages/circle/home/components/WebSlider/CircleWebSlider.tsx
  src/pages/circle/home/components/WebSlider/index.ts
  src/pages/circle/home/components/index.ts
Labels: fix, feat

#86 [FEAT] 학생회 QA 대비 기능 유지보수 중간 배포
  src/@types/board.d.ts
  src/@types/home.d.ts
  src/@types/user.d.ts
  src/components/Form/StyledInput.tsx
  src/components/Layout.ts
  src/configs/axios.ts
  src/configs/path.ts
  src/mocks/data/setting.ts
  src/mocks/handlers/index.ts
  src/mocks/handlers/settingHandler.ts
  src/pages/auth/signIn/SignInPage.tsx
  src/pages/board/BoardPageSwitch.tsx
  src/pages/board/boardCreate/BoardCreatePage.tsx
  src/pages/board/boardCreate/BoardCreatePageUiStore.ts
  src/pages/board/boardList/BoardListPage.tsx
  src/pages/board/boardList/BoardListPageUiStore.ts
  src/pages/board/boardList/components/BoardCreateButton.tsx
  src/pages/board/boardList/components/BoardListItem.tsx
  src/pages/board/boardList/components/Boards.tsx
  src/pages/board/boardList/components/DeleteBoardModal/DeleteBoardModal.tsx
  src/pages/board/boardList/components/DeleteBoardModal/DeleteBoardModalUi.ts
  src/pages/board/boardList/components/DeleteBoardModal/index.ts
  src/pages/board/boardList/components/index.ts
  src/pages/board/boardList/components/styled.tsx
  src/pages/board/boardList/index.ts
  src/pages/setting/home/SettingHomePage.tsx
  src/pages/setting/roleManagement/SettingRoleManagementPage.tsx
  src/pages/setting/roleManagement/SettingRoleManagementPageUiStore.ts
  src/pages/setting/roleManagement/components/PresidentUsers.tsx
  src/pages/setting/roleManagement/components/index.ts
  src/pages/setting/users/components/ActiveUserTab/ActiveUserTab.tsx
  src/pages/setting/users/components/ActiveUserTab/ActiveUserTabUi.tsx
  src/pages/setting/users/components/AdmissionUserTab/AdmissionUserTab.tsx
  src/pages/setting/users/components/AdmissionUserTab/AdmissionUserTabUi.tsx
  src/pages/setting/users/components/InactiveUserTab/InactiveUserTab.tsx
  src/pages/setting/users/components/InactiveUserTab/InactiveUserTabUi.tsx
  src/stores/models/BoardModel.ts
  src/stores/models/PostModel.ts
  src/stores/repositories/AuthRepo.ts
  src/stores/repositories/BoardRepo.ts
  src/stores/repositories/HomeRepo.ts
  src/stores/repositories/UserRepo.ts
  src/vite-env.d.ts
Labels: fix, feat, refactor

#88 [FEAT] 학생회 QA 대비 기능 유지보수 중간 배포 2차
  src/@types/user.d.ts
  src/AuthRouter.tsx
  src/configs/path.ts
  src/pages/auth/AuthPageSwitch.tsx
  src/pages/auth/findPassword/FindPasswordPage.tsx
  src/pages/auth/findPassword/FindPasswordPageUiStore.ts
  src/pages/auth/findPassword/index.ts
  src/pages/auth/signIn/SignInPage.tsx
  src/pages/auth/signUp/SignUpPage.tsx
  src/pages/board/boardCreate/BoardCreatePage.tsx
  src/pages/board/boardList/BoardListPage.tsx
  src/pages/board/boardList/BoardListPageUiStore.ts
  src/pages/board/boardList/components/BoardCreateButton.tsx
  src/stores/repositories/AuthRepo.ts
  src/vite-env.d.ts
Labels: fix, feat

#89 [FEAT] 학생회 QA 대비 기능 유지보수 중간 배포 3차
  src/configs/axios.ts
  src/configs/path.ts
  src/pages/auth/admission/SubmitButton.tsx
  src/pages/auth/findPassword/FindPasswordPage.tsx
  src/pages/auth/findPassword/FindPasswordPageUiStore.ts
  src/pages/auth/signUp/SignUpPage.tsx
  src/pages/board/boardCreate/BoardCreatePage.tsx
  src/pages/board/boardList/components/DeleteBoardModal/DeleteBoardModal.tsx
  src/pages/locker/list/components/LockerPosition/LockerPosition.tsx
  src/pages/setting/roleManagement/components/PresidentUsers.tsx
  src/pages/setting/roleManagement/components/styled.tsx
  src/stores/repositories/StorageRepo.ts
  src/utils/reg.ts
Labels: fix, feat

#104 [CHORE] README 작성
  README.md
  index.html
  package-lock.json
  package.json
  public/favicon.ico
  public/icon/android-icon-192x192.png
  public/icon/apple-icon-114x114.png
  public/icon/apple-icon-120x120.png
  public/icon/apple-icon-144x144.png
  public/icon/apple-icon-152x152.png
  public/icon/apple-icon-180x180.png
  public/icon/apple-icon-57x57.png
  public/icon/apple-icon-60x60.png
  public/icon/apple-icon-72x72.png
  public/icon/apple-icon-76x76.png
  public/icon/favicon-16x16.png
  public/icon/favicon-32x32.png
  public/icon/favicon-96x96.png
  public/icon/ms-icon-144x144.png
  public/manifest.json
  src/configs/axios.ts
  src/index.tsx
  src/mocks/handlers/settingHandler.ts
  src/pages/auth/AuthPageSwitch.tsx
  src/pages/auth/noPermission/NoPermissionPage.tsx
  src/pages/auth/noPermission/NoPermissionPageUiStore.tsx
  src/pages/auth/noPermission/index.ts
  src/pages/board/postDetail/components/CommentInput/CommentInputContainer.tsx
  src/stores/repositories/UserRepo.ts
  yarn.lock
Labels: chore

#105 [CHORE] README 작성
  README.md
Labels: chore

#107 [HOTFIX] 사물함 UI 및 라우터 로직 수정
  README.md
  src/pages/locker/locations/components/LockerApplicationModal/LockerApplicationModal.tsx
  src/pages/locker/locations/components/SubmitButton/SubmitButton.tsx
Labels: hotfix

#108 [HOTFIX] 사물함 UI 및 라우터 로직 수정 (운영)
  README.md
  src/pages/locker/locations/components/LockerApplicationModal/LockerApplicationModal.tsx
  src/pages/locker/locations/components/SubmitButton/SubmitButton.tsx
Labels: hotfix

#110 [DESIGN] 동아리 관련 페이지 웹 반응형 디자인
  package-lock.json
  package.json
  src/hooks/index.ts
  src/hooks/useDeviceState.tsx
  src/pages/circle/home/CircleHomePage.tsx
  src/pages/circle/home/components/MobileSlider/CircleMobileSlideCard.tsx
  src/pages/circle/home/components/MobileSlider/CircleMobileSlider.tsx
  src/pages/circle/home/components/MobileSlider/index.ts
  src/pages/circle/home/components/Slider/index.ts
  src/pages/circle/home/components/WebSlider/CircleWebSlideCard.tsx
  src/pages/circle/home/components/index.ts
  yarn.lock
Labels: fix, docs, design

#114 hotfix: removed admission number input field
  src/pages/auth/signUp/SignUpPage.tsx
Labels: hotfix

#115 merge #113, #109
  package-lock.json
  package.json
  src/hooks/index.ts
  src/hooks/useDeviceState.tsx
  src/pages/auth/signUp/SignUpPage.tsx
  src/pages/circle/home/CircleHomePage.tsx
  src/pages/circle/home/components/MobileSlider/CircleMobileSlideCard.tsx
  src/pages/circle/home/components/MobileSlider/CircleMobileSlider.tsx
  src/pages/circle/home/components/MobileSlider/index.ts
  src/pages/circle/home/components/Slider/index.ts
  src/pages/circle/home/components/WebSlider/CircleWebSlideCard.tsx
  src/pages/circle/home/components/index.ts
  yarn.lock
Labels: design, hotfix

#121 [FEAT] PWA builder setting
  public/manifest.json
Labels: feat
