Repository CAUCSE/CAUSW_frontend, pull requests merged in 2024-01, with the labels that each got.

#28 [CHORE] issue & PR template 생성
  .github/issue_template.md
  .github/pull_request_template.md
Labels: chore

#32 [FEAT] msw 적용하여 API mocking (home, board)
  .eslintrc.cjs
  package-lock.json
  package.json
  public/mockServiceWorker.js
  src/@types/home.d.ts
  src/@types/post.d.ts
  src/components/Gnb/GnbContainer.tsx
  src/hooks/usePageUiStore.tsx
  src/index.tsx
  src/mocks/browser.ts
  src/mocks/handler.ts
  src/pages/auth/signIn/SignInPage.tsx
  src/pages/board/postDetail/PostDetailPage.tsx
  src/pages/board/postDetail/PostDetailPageUiStore.tsx
  src/pages/board/postList/PostListPage.tsx
  src/pages/board/postList/components/PostCard.tsx
  src/pages/home/HomePage.tsx
  src/pages/home/components/HomeBoardListItem.tsx
  src/stores/models/PostModel.ts
  src/stores/repositories/CommentRepo.ts
  src/stores/repositories/HomeRepo.ts
  src/stores/repositories/PostRepo.ts
  yarn.lock
Labels: feat

#36 [FEAT] msw circle API mocking
  src/@types/circle.d.ts
  src/mocks/circleHandler.ts
  src/mocks/handler.ts
  src/mocks/homeHandler.ts
  src/mocks/mockData.ts
  src/mocks/postHandler.ts
  src/stores/repositories/CircleRepo.ts
Labels: feat

#39 [REFACTOR] 코드 스플리팅을 통해 초기 로딩속도 개선
  .eslintrc.cjs
  index.html
  package-lock.json
  package.json
  public/_redirects
  src/PageRouter.tsx
  src/components/Header/index.ts
  src/components/Loading.tsx
  src/components/StyledPost.tsx
  src/index.tsx
  src/pages/auth/signIn/SignInPage.tsx
  src/pages/board/BoardPageSwitch.tsx
  src/pages/board/postEditor/styled.ts
  src/pages/circle/CirclePageSwitch.tsx
  src/pages/circle/home/components/Slider/CircleSlider.tsx
  src/pages/index.ts
  vite.config.ts
  yarn.lock
Labels: feat, refactor

#47 [FEAT] board, circle, comment msw mocking
  index.html
  package.json
  src/mocks/browser.ts
  src/mocks/circleHandler.ts
  src/mocks/handler.ts
  src/mocks/handlers/boardHandler.ts
  src/mocks/handlers/circleHandler.ts
  src/mocks/handlers/commentHandler.ts
  src/mocks/handlers/historyHandler.ts
  src/mocks/handlers/homeHandler.ts
  src/mocks/handlers/index.ts
  src/mocks/handlers/lockerHandler.ts
  src/mocks/handlers/postHandler.ts
  src/mocks/homeHandler.ts
  src/mocks/mockData.ts
  src/mocks/postHandler.ts
  src/pages/board/postDetail/PostDetailPageUiStore.tsx
  src/pages/board/postDetail/components/Comment/CommentCardContainer.tsx
  src/pages/board/postDetail/components/CommentInput/CommentInputView.tsx
  src/pages/board/postEditor/PostEditorPageUiStore.ts
  src/pages/board/postEditor/components/Editor.tsx
  src/stores/repositories/BoardRepo.ts
  src/stores/repositories/CircleRepo.ts
  src/stores/repositories/CommentRepo.ts
  src/stores/repositories/PostRepo.ts
Labels: feat, refactor

#49 [FEAT] reply-comment API mocking
  src/@types/board.d.ts
  src/@types/comment.d.ts
  src/@types/replyComment.d.ts
  src/components/Gnb/GnbContainer.tsx
  src/global-styles.ts
  src/mocks/handlers/boardHandler.ts
  src/mocks/handlers/circleHandler.ts
  src/mocks/handlers/commentHandler.ts
  src/mocks/handlers/data/board.ts
  src/mocks/handlers/data/circle.ts
  src/mocks/handlers/data/comment.ts
  src/mocks/handlers/data/history.ts
  src/mocks/handlers/data/locker.ts
  src/mocks/handlers/data/post.ts
  src/mocks/handlers/data/replyComment.ts
  src/mocks/handlers/historyHandler.ts
  src/mocks/handlers/homeHandler.ts
  src/mocks/handlers/lockerHandler.ts
  src/mocks/handlers/postHandler.ts
  src/mocks/mockData.ts
  src/stores/models/CommentModel.ts
  src/stores/models/PostCommentModel.ts
  src/stores/repositories/BoardRepo.ts
  src/stores/repositories/BoardType.ts
  src/stores/repositories/CommentRepo.ts
  src/stores/repositories/ReplyCommentRepo.ts
Labels: feat

#50 [FEAT] msw setting API mocking
  src/mocks/handlers/circleHandler.ts
  src/mocks/handlers/commentHandler.ts
  src/mocks/handlers/data/history.ts
  src/mocks/handlers/data/locker.ts
  src/mocks/handlers/data/setting.ts
  src/mocks/handlers/historyHandler.ts
  src/mocks/handlers/index.ts
  src/mocks/handlers/lockerHandler.ts
  src/mocks/handlers/settingHandler.ts
  src/pages/setting/home/SettingHomePage.tsx
  src/pages/setting/users/components/ActiveUserTab/ActiveUserTab.tsx
  src/stores/models/UserModel.ts
  src/stores/repositories/AuthRepo.ts
  src/stores/repositories/CircleRepo.ts
  src/stores/repositories/LockerRepo.ts
  src/stores/repositories/UserRepo.ts
Labels: feat

#54 [DESIGN] Locker, setting, history page 반응형 디자인 개선
  src/components/ListBox.tsx
  src/mocks/handlers/data/history.ts
  src/mocks/handlers/data/locker.ts
  src/pages/history/comment/HistoryCommentPage.tsx
  src/pages/history/comment/components/HistoryCommentCard.tsx
  src/pages/history/post/HistoryPostPage.tsx
  src/pages/history/post/components/HistoryPostCard.tsx
  src/pages/locker/locations/components/LocationGrid/LocationGrid.tsx
  src/pages/locker/locations/components/LocationGrid/styled.ts
  src/pages/setting/home/SettingHomePage.tsx
Labels: design
