Repository CAUCSE/CAUSW_frontend, pull requests merged in 2024-02, with the labels that each got.

#58 [FIX] board API 검증 및 연동 (게시판 조회 + 생성, 수정, 삭제, 복구)
  src/@types/board.d.ts
  src/mocks/data/board.ts
  src/mocks/data/circle.ts
  src/mocks/data/comment.ts
  src/mocks/data/history.ts
  src/mocks/data/locker.ts
  src/mocks/data/post.ts
  src/mocks/data/replyComment.ts
  src/mocks/data/setting.ts
  src/mocks/handlers/boardHandler.ts
  src/mocks/handlers/circleHandler.ts
  src/mocks/handlers/commentHandler.ts
  src/mocks/handlers/data/board.ts
  src/mocks/handlers/historyHandler.ts
  src/mocks/handlers/homeHandler.ts
  src/mocks/handlers/lockerHandler.ts
  src/mocks/handlers/postHandler.ts
  src/mocks/handlers/settingHandler.ts
  src/pages/board/boardList/BoardListPageUiStore.ts
  src/stores/repositories/BoardRepo.ts
Labels: fix

#61 [FEAT] playwright E2E 테스트 적용: basic setting
  .eslintrc.cjs
  .github/workflows/playwright.yml
  .gitignore
  package-lock.json
  package.json
  playwright.config.ts
  tests/tester/lockerTester.ts
  tests/tester/settingTester.ts
  tests/tester/signinTester.ts
  tests/tests.spec.ts
  yarn.lock
Labels: feat

#63 [FEAT] playwright E2E 테스트 적용 (board)
  .eslintrc.cjs
  package-lock.json
  package.json
  src/@types/comment.d.ts
  src/@types/replyComment.d.ts
  src/mocks/data/replyComment.ts
  src/mocks/handlers/postHandler.ts
  src/pages/board/boardList/BoardListPage.tsx
  src/pages/board/postDetail/components/Comment/CommentCardContainer.tsx
  src/pages/board/postDetail/components/Comment/CommentCardView.tsx
  src/pages/board/postDetail/components/CommentInput/CommentInputView.tsx
  src/pages/board/postDetail/components/CommentMenu/CommentMenuContainer.tsx
  src/pages/board/postDetail/components/ReplyComment/PostReplyComments.tsx
  src/pages/board/postDetail/components/ReplyComment/ReplyCommentContainer.tsx
  src/pages/board/postEditor/PostEditorPage.tsx
  src/pages/board/postEditor/PostEditorPageUiStore.ts
  src/pages/board/postEditor/components/Editor.tsx
  src/stores/models/CommentModel.ts
  src/stores/models/PostCommentModel.ts
  src/stores/repositories/CommentRepo.ts
  src/vite-env.d.ts
  tests/tester/boardTester.ts
  tests/tester/lockerTester.ts
  tests/tester/settingTester.ts
  tests/tests.spec.ts
  tsconfig.json
  vite.config.ts
  yarn.lock
Labels: feat

#67 [FIX] post API 검증 및 코드 개선 (조회, 생성, 수정, 삭제, 검색 + 복구)
  src/@types/post.d.ts
  src/hooks/useInputs.ts
  src/pages/board/postDetail/PostDetailPageUiStore.tsx
  src/pages/board/postDetail/components/PostDeleteModal/PostDeleteModal.tsx
  src/pages/board/postEditor/PostEditorPageUiStore.ts
  src/pages/board/postList/PostListPage.tsx
  src/pages/board/postList/PostListPageUiStore.ts
  src/pages/board/postList/components/PostSearchForm.tsx
  src/stores/models/PostModel.ts
  src/stores/repositories/PostRepo.ts
Labels: fix, refactor

#73 [FIX] User API 검증, Mocking 해제
  src/@types/history.d.ts
  src/@types/user.d.ts
  src/AuthRouter.tsx
  src/configs/axios.ts
  src/index.tsx
  src/pages/setting/home/SettingHomePage.tsx
  src/stores/AuthStore.tsx
  src/stores/models/AdmissionUserModel.ts
  src/stores/models/HistoryCommentModel.ts
  src/stores/models/HistoryPostModel.ts
  src/stores/models/UserModel.ts
  src/stores/repositories/AuthRepo.ts
  src/stores/repositories/CommentRepo.ts
  src/stores/repositories/HomeRepo.ts
  src/stores/repositories/LockerRepo.ts
  src/stores/repositories/ReplyCommentRepo.ts
  src/stores/repositories/UserRepo.ts
Labels: fix, refactor

#75 [FIX] User API 권한 변경 관련 수정
  src/pages/setting/home/SettingHomePage.tsx
  src/pages/setting/roleDelegation/SettingRoleDelegationPage.tsx
  src/pages/setting/roleDelegation/SubmitButton.tsx
  src/pages/setting/roleLeaderCircle/SettingRoleLeaderCirclePageUiStore.ts
Labels: fix

#77 [FEAT] Netlify 배포 환경 구성 (개발계)
  .github/workflows/playwright.yml
  index.html
  netlify.toml
  public/favicon-16x16.png
  public/favicon-96x96.png
  src/configs/axios.ts
Labels: feat

#80 [REFACTOR] Refresh token 도입, Locker API 검증
  src/@types/locker.d.ts
  src/@types/user.d.ts
  src/AuthRouter.tsx
  src/configs/axios.ts
  src/index.tsx
  src/mocks/data/locker.ts
  src/mocks/handlers/authHandler.ts
  src/mocks/handlers/index.ts
  src/pages/locker/list/components/LockerListCard/LockerListCard.tsx
  src/pages/locker/list/components/LockerPosition/LockerPosition.tsx
  src/pages/locker/locations/components/LocationGrid/LocationCell.tsx
  src/stores/AuthStore.tsx
  src/stores/models/LockerLocationModel.ts
  src/stores/models/LockerModel.ts
  src/stores/repositories/AuthRepo.ts
  src/stores/repositories/LockerRepo.ts
Labels: fix, feat, refactor

#82 [REFACTOR] Refresh token 도입, Locker API 검증
  src/@types/locker.d.ts
  src/@types/user.d.ts
  src/AuthRouter.tsx
  src/configs/axios.ts
  src/index.tsx
  src/mocks/data/locker.ts
  src/mocks/handlers/authHandler.ts
  src/mocks/handlers/index.ts
  src/pages/locker/list/components/LockerListCard/LockerListCard.tsx
  src/pages/locker/list/components/LockerPosition/LockerPosition.tsx
  src/pages/locker/locations/components/LocationGrid/LocationCell.tsx
  src/pages/setting/home/SettingHomePage.tsx
  src/pages/setting/roleDelegation/SettingRoleDelegationPage.tsx
  src/pages/setting/roleDelegation/SubmitButton.tsx
  src/pages/setting/roleLeaderCircle/SettingRoleLeaderCirclePageUiStore.ts
  src/stores/AuthStore.tsx
  src/stores/models/LockerLocationModel.ts
  src/stores/models/LockerModel.ts
  src/stores/repositories/AuthRepo.ts
  src/stores/repositories/LockerRepo.ts
Labels: fix, feat, refactor
